### ISSUE TITLE
Verbose argument

### ISSUE THREAD

**Issue by alexpiper** [kr-colab/locator#14]
Would it be possible to add a --verbose argument to locator that is passed on to keras model.fit verbose option? The model fitting progress bar doesn't seem to play nicely with SLURM job scripts and is printing over 200k lines into the stdout file. Obviously not an urgent issue, just a slight annoyance.

Cheers,
Alex

**Comment by cjbattey** [comment]
good idea -- the current setting is a mess for logging. This PR added a new argument to pass the keras verbose setting:  https://github.com/kr-colab/locator/pull/15. 0 is silent, 1 is the current setting, 2 just prints the epochs without the progress bars. You should be able to install the new version by following the github install instructions in the readme.

**Comment by alexpiper** [comment]
Perfect, thanks CJ!
