### ISSUE TITLE
Issue: sample data matches, but sample ordering failed! message still appears

### ISSUE THREAD

**Issue by clararehmann** [kr-colab/locator#16]
Hi,

I'm working with genotypes in .zarr format - sample IDs in the Zarr array have been written directly from the metadata file, and I am reading them into Locator as strings with `.astype('str')` appended to `samples = callset['samples'][:]`. Sample IDs match the metadata according to my test script, but when I run Locator, I get the following error message:

    sample ordering failed! Check that sample IDs match the VCF.

#### Reproducing code example

    $ python test.py
    > no output
    $ python locator/scripts/locator.py --zarr zarr/2L.zarr --sample_data ag1000g3_sample.txt --out out --windows --window_size 2000000
    > sample ordering failed! Check that sample IDs match the VCF.

[issue.zip](https://github.com/kr-colab/locator/files/5313956/issue.zip)

Thanks!

**Comment by andrewkern** [comment]
hey @clararehmann. i found the issue on the locator side. PR #17 closes this out.
